Provides a curl | bash installer
nVentiveUX/docker-syncthing pull request #7
Opened 2017-01-11 23:02 UTC by bigbrozer

Yo my friend !
Please have a look to this PR that add a `curl | bash` installer.

I have tested it using Python 3's http module:

```shell
$ python3 -m http.server 8080
```

You need then to adapt the `GITHUB_ROOT` variable in `installer.sh` and launch the installer with:

```shell
$ curl -sSL http://<IP_PYTHON_HOST>:8080/installer.sh | sudo bash
```

## Known issues

* The image pulling is failing because the docker image is not (yet) available on **Docker Hub**.
    * As a workaround, comment call to function `pull_image` in `installer.sh`.

## Notable changes

* I have reworked the README to make use of it.

* We use now `<image>:latest` tag everywhere. This is strongly linked to **master** branch (stable, prod).

* We now have a single instance service in systemd, see `docker-syncthing` service.

* Systemd services have now a new `PORTS` environment variable which permit the redefinition (per instances / single instance) of port mapping between host and container(s).
    * `PORTS` variable is set by default through the service definition `Environment` option. You can override it using `/etc/default/docker-syncthing` (single instance) or `/etc/default/docker-syncthing@<INSTANCE_NAME>` (multiple instances).

2017-01-11 23:04 UTC, bigbrozer commented
If merged, will close #6.

2017-01-12 14:03 UTC, link-webcreations commented on installer.sh
> +    systemctl enable docker-syncthing.service
Do not enable single user service by default. Let the choice to the user.

2017-01-12 14:03 UTC, link-webcreations commented on installer.sh
> +function start_syncthing_service() {
Do not start any service by default. Let the choice to the user.

2017-01-12 14:08 UTC, link-webcreations commented on README.md
> +Use `/syncedfolders` to store synced content to the syncthing container:
This is an important thing to know for everybody. You can make it more visible.

2017-01-12 14:15 UTC, link-webcreations requested changes

2017-01-12 14:15 UTC, link-webcreations commented on README.md
> +Use `/syncedfolders` to store synced content to the syncthing container:
This is an important thing to know for everybody. You can make it more visible.

2017-01-12 14:15 UTC, link-webcreations commented on installer.sh
> +    systemctl enable docker-syncthing.service
Do not enable single user service by default. Let the choice to the user.

2017-01-12 14:15 UTC, link-webcreations commented on installer.sh
> +function start_syncthing_service() {
Do not enable single user service by default. Let the choice to the user.

2017-01-24 15:55 UTC, bigbrozer commented on README.md
> +Use `/syncedfolders` to store synced content to the syncthing container:
Re-written **Quick Install** section.

2017-01-24 15:56 UTC, bigbrozer commented on installer.sh
> +    systemctl enable docker-syncthing.service
See 920dcb2.

2017-01-24 15:56 UTC, bigbrozer commented on installer.sh
> +function start_syncthing_service() {
See 920dcb2.

2017-01-25 21:08 UTC, merged